name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install  

    - name: Generate index.html
      run: node index.js  

    - name: Duplicate index.html
      run: |
        mkdir dist
        cp -r ./src ./dist
        cp ./index.html ./dist
        cp ./style.css ./dist


    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        # ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Settings > Secret 建立的 ACCESS_TOKEN，推同個 repo 的話可以不需要
        BRANCH: gh-pages # deploy 到 gh-pages 這個分支
        FOLDER: dist # build 後的資料夾
